language: php

php:
  - 5.3

before_script:
  # export virtual display
  - export DISPLAY=:99

  # change application working folders for write access
  - chmod -R 0777 ./tmp
  - chmod -R 0777 ./uploads
  - chmod -R 0777 ./templates/cache/
  - chmod -R 0777 ./templates/compiled/
  - rm -rf install/

  # install required PHP stuff
  - sudo apt-get install php5 php5-cli php5-mysql php5-mcrypt php5-xsl php5-xdebug php-apc php5-gd php5-curl php5-intl 

  # launch apache, MySQL and PHPUnit Selenium installers
  - ./tests/travis/apache_setup.sh
  - ./tests/travis/mysql_setup.sh
  - mysql -u root -e "USE social_test; SHOW TABLES;"
  - cp ./config/config.test.php.dist config/config.test.php
  - cp ./config/config.test.php.dist config/config.local.php
  - sudo sed -i s/sql-mode/#sql-mode/ /etc/mysql/my.cnf
  - sudo /etc/init.d/mysql restart
  - sleep 5

  # get HTML of main page (for debug)
  - firefox --version
  - wget -O /tmp/livestreet.test http://livestreet.test
  - cat /tmp/livestreet.test

  # start virtual display
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # download and launch Selenium
  - wget -O /tmp/selenium-server-standalone.jar http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar /tmp/selenium-server-standalone.jar > /dev/null &
  - sleep 5

  # goto test's folder
  - cd tests/behat/

script: HTTP_APP_ENV=test php behat.phar
